# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
jobs:
  - job: LinuxBuild
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - checkout: self
      submodules: true
    - script: |
        sudo sh ./.azure-pipelines-scripts/before_install.sh
        sudo sh ./.azure-pipelines-scripts/install.sh
        sudo sh ./.azure-pipelines-scripts/script-linux.sh
        sudo sh ./.azure-pipelines-scripts/script-macos.sh
        sudo sh ./.azure-pipelines-scripts/script-win32.sh
        sudo sh ./.azure-pipelines-scripts/script-win64.sh
      displayName: 'Building'
  # - job: MacBuild
  #   pool:
  #     vmImage: 'macOS-10.13'
  #   steps:
  #   - checkout: self
  #     submodules: true
  #   - script: |
  #       make
  #     displayName: 'Building'
  # - job: WinBuild
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   steps:
  #   - checkout: self
  #     submodules: true
  #   - script: | 
  #       vcpkg install opengl
  #       vcpkg integrate install #to make available installed packages
  #     displayName: Vcpkg install dependencies
  #   - script: |
  #       make
  #     displayName: 'Building'


